# -*- mode: ruby -*-
# # vi: set ft=ruby :

Vagrant.configure(2) do |config|

  (1..3).each do |i|
    config.vm.define "k8s#{i}" do |s|
      s.ssh.forward_agent = true
      s.vm.box = "jibijose/ubuntu18k8s"
      s.vm.hostname = "k8s#{i}"
      s.vm.network "private_network", ip: "192.168.56.10#{i}", netmask: "255.255.255.0", auto_config: true, virtualbox__intnet: "k8s-net"
      s.vm.provider "virtualbox" do |v|
        v.name = "k8s#{i}"
        v.cpus = 2
        v.memory = 2048
        v.gui = false
      end

      if i == 1
        s.vm.provision :shell, path: "scripts/bootstrap_master.sh"
      else
        s.vm.provision :shell, path: "scripts/bootstrap_worker.sh"
      end
    end
  end

end
