Vagrant.require_version ">= 1.4.3"
VAGRANTFILE_API_VERSION = "2"
NUM_OF_NODES = defined?(CUSTOM_NUM_OF_NODES) ? CUSTOM_NUM_OF_NODES : 1
NODE_NAME = defined?(CUSTOM_NODE_NAME) ? CUSTOM_NODE_NAME : "node"
NODE_START_IP = defined?(CUSTOM_NODE_START_IP) ? CUSTOM_NODE_START_IP : "192.168.56.100"
NODE_SSHPORT_START = defined?(CUSTOM_NODE_SSHPORT_START) ? CUSTOM_NODE_SSHPORT_START : 2000
NODE_MEMORY = defined?(CUSTOM_NODE_MEMORY) ? CUSTOM_NODE_MEMORY : 1024
NODE_CPU = defined?(CUSTOM_NODE_CPU) ? CUSTOM_NODE_CPU : 1

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	r = NUM_OF_NODES..1
	(r.first).downto(r.last).each do |i|
		if NUM_OF_NODES == 1
		  NAME = "#{NODE_NAME}"
	    else
		  NAME = "#{NODE_NAME}#{i}"
	    end
		config.vm.define "#{NAME}" do |node|
			node.vm.box = "ubuntu/bionic64"
			node.vm.box_check_update = false
			node.vm.provider "virtualbox" do |v|
			  v.name = "#{NAME}"
			  v.customize ["modifyvm", :id, "--memory", "#{NODE_MEMORY}"]
			  v.customize ["modifyvm", :id, "--cpus", "#{NODE_CPU}"]
			  v.customize ["modifyvm", :id, "--groups", "/VagrantLinux"]
			  v.customize ["modifyvm", :id, "--usb", "on"]
			  v.customize ["modifyvm", :id, "--usbehci", "off"]
			end
			
			import_vagrantfile = File.expand_path('../../vagrant-scripts/Vagrantfile.common.import', __FILE__)
            eval File.read(import_vagrantfile) if File.exists?(import_vagrantfile)
			
			node.vm.provision "shell", inline: <<-SHELL
				echo "ubuntu:ubuntu" | sudo chpasswd
			SHELL
			node.vm.provision "shell", privileged: true, inline: <<-SHELL
				echo "root:ubuntu" | sudo chpasswd
			SHELL
			
			node.vm.provision "shell", inline: "apt-get update -qq"
			node.vm.provision "shell", inline: "apt-get install -y -qq sshpass"
			node.vm.provision "shell", inline: "apt-get install -y -qq wget"
			
			node.vm.provision "shell", path: "../unix-scripts/ubuntu/setup-ubuntu-root-vms.sh"
			node.vm.provision "shell", path: "../unix-scripts/ubuntu/setup-ubuntu-vagrant-vms.sh", privileged:false
		end
	end
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	r = NUM_OF_NODES..1
	(r.first).downto(r.last).each do |i|
	    config.vm.define "#{NAME}" do |node|
	        node.vm.provision "shell" do |s|
				s.path = "../unix-scripts/setup-root-hosts.sh"
				s.args = "-t #{NUM_OF_NODES} -n #{NODE_NAME} -i #{NODE_START_IP}"
			end
			if i == 1
			    node.vm.provision "shell" do |s|
				  s.path = "../unix-scripts/ubuntu/setup-ubuntu-root-ssh.sh"
				  s.args = "-t #{NUM_OF_NODES} -n #{NODE_NAME} -i #{NODE_START_IP}"
			    end
				node.vm.provision "shell" do |s|
				  s.path = "../unix-scripts/ubuntu/setup-ubuntu-vagrant-ssh.sh"
				  s.privileged = false
				  s.args = "-t #{NUM_OF_NODES} -n #{NODE_NAME} -i #{NODE_START_IP}"
			    end
			end
		end		
	end
end