CUSTOM_NUM_OF_NODES=4
CUSTOM_NODE_NAME="couchbase"
CUSTOM_NODE_START_IP="192.168.56.110"
CUSTOM_NODE_SSHPORT_START=2110
CUSTOM_NODE_MEMORY=1024
CUSTOM_NODE_CPU=2

load '../vagrant-centos-cluster/Vagrantfile'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

	r = NUM_OF_NODES..1
	(r.first).downto(r.last).each do |i|
		config.vm.define "#{NODE_NAME}#{i}" do |node|
			node.vm.provision "shell", path: "scripts/install-couchbase.sh"
			node.vm.provision "shell", path: "scripts/setup-couchbase.sh"
		end
	end
end