
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_check_update = true
  
  config.vm.provider "virtualbox" do |v|
        v.name = "k8sbase"
        v.cpus = 2
        v.memory = 2048
        v.gui = false
      end

    config.vm.provision :shell, path: "scripts/bootstrap_base.sh"
end
